<Project Sdk="Microsoft.NET.Sdk">
  <!--
    Camada Infrastructure — EF Core, JWT, repos. Plugin da Application.
    FrameworkReference AspNetCore.App habilita HttpContext/middleware.
  -->
  <ItemGroup>
    <ProjectReference Include="..\Wrench.Application\Wrench.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
  </ItemGroup>
</Project>
